# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a70bbc7c-e23b-444a-a1f1-c9246196c357";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9ceac3fe-b7ee-41b5-a14c-39bb40727fb4".device = "/dev/disk/by-uuid/9ceac3fe-b7ee-41b5-a14c-39bb40727fb4";
  boot.initrd.luks.devices."luks-a70bbc7c-e23b-444a-a1f1-c9246196c357".device = "/dev/disk/by-uuid/a70bbc7c-e23b-444a-a1f1-c9246196c357";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1DC2-1D3F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9ceac3fe-b7ee-41b5-a14c-39bb40727fb4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
