# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4231fe5d-d73d-4a6d-b544-d328e4c4e7e8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-65c9be39-000d-4c05-9961-f8c8004d5b05".device = "/dev/disk/by-uuid/65c9be39-000d-4c05-9961-f8c8004d5b05";
  boot.initrd.luks.devices."luks-ed2b12de-1604-4326-9bc0-c477b8463779".device = "/dev/disk/by-uuid/ed2b12de-1604-4326-9bc0-c477b8463779";


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/251C-C350";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/450639d3-2be2-465e-a20e-927962926e03"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
