# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7b4ca5ba-4c2e-4379-b9a9-2835b31bb52b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9865ef4e-495d-414a-be04-8fc6f12d5930".device = "/dev/disk/by-uuid/9865ef4e-495d-414a-be04-8fc6f12d5930";
  boot.initrd.luks.devices."luks-d156ad59-2a91-40dd-95d5-c0c991e363cf".device = "/dev/disk/by-uuid/d156ad59-2a91-40dd-95d5-c0c991e363cf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F576-B67A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cb1e733d-3319-451d-8a44-f1810abefbd3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
