# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/38d00244-12a9-45cd-8d70-436d3e5c67ec";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e03a01d6-a98f-4af7-bb38-705bb3b788b0".device = "/dev/disk/by-uuid/e03a01d6-a98f-4af7-bb38-705bb3b788b0";
  boot.initrd.luks.devices."luks-082a2110-01a3-4edd-8947-0749797bed3b".device = "/dev/disk/by-uuid/082a2110-01a3-4edd-8947-0749797bed3b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/982E-2C99";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/590a9021-7669-444e-8236-8f9306dbc556"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

